name: New Bug
description: Create a bug on this repo
title: "Bug Name"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of what happened and what should have happened
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Remember to create a branch off this issue under the `Development` section to the right after submitting.