name: Project Feature
description: Link a new feature to a project
title: "Feature Name"
labels: ["enhancement"]
body:
  - type: input
    id: project
    attributes:
      label: Project Link
      description: Please place the link to the project's issue in the rebel-projects repo here
    validations:
      required: true